### ISSUE TITLE
Custom preambule: not such file or directory

### ISSUE THREAD

**Issue by tobiasBora** [ghseeli/latex2blender#10]
I don't know why, but in some files I get this error `os.getcwd(): no such file or directory`. (tested on blender 3.1, with the master version https://github.com/ghseeli/latex2blender/commit/402fc2a92a9ca0015139545260373e5626a7d2bc)

![image](https://user-images.githubusercontent.com/2164118/158766109-a803c885-4e29-4d05-a4dc-fa2cada98c5d.png)

**Comment by tobiasBora** [comment]
Typically, this starts when I try to add a custom preambule:

![image](https://user-images.githubusercontent.com/2164118/158767909-6e7f2b8d-f3fe-4df1-b0cc-88ebbd51cbd7.png)

![image](https://user-images.githubusercontent.com/2164118/158767605-31b37f0c-1d05-42a3-a945-b3e28835efbc.png)

I first get an error:

![image](https://user-images.githubusercontent.com/2164118/158768425-420549b2-19b3-483e-98cf-60140ae094f6.png)

And then the above bug fires until I restart completely blender and disable the custom preambule.

**Comment by ghseeli** [comment]
Thank you for pointing this out! This is definitely something we need to fix. I am a bit swamped with other tasks at the moment, but I will see if we can get it working in the next few weeks!

**Comment by tobiasBora** [comment]
Sure, no worries there is no need to have a quick fix (and I may as well try to fix it at some points) since there is a workaround.

**Comment by peterkj1** [comment]
I have fixed this bug. I have not yet made a new release, but the updated latex2blender.py file has the fix. Now the add-on automatically converts relative paths to absolute paths.
