### ISSUE TITLE
\left and \right problem

### ISSUE THREAD

**Issue by HomayoonT** [ghseeli/latex2blender#21]
![left-right-latex-2-blender-problem](https://github.com/ghseeli/latex2blender/assets/74807046/65dc6bd5-4dfc-4bc2-98c8-6f7d6bc9792d)

I used the LaTeX code `\left| x^2 \right|`. There appear holes for the `\left|` and `\right|`.

**Comment by peterkj1** [comment]
I think I fixed this issue in the newest release (1.0.7). If the problem persists, please let me know.
