### ISSUE TITLE
Compilation error on Ubuntu 24.04.1

### ISSUE THREAD

**Issue by 1-Bart-1** [ghseeli/latex2blender#25]
I am getting a compilation error on Ubuntu 24.04.1 LTS. LaTeX and dvisvgm work fine, I tested using them and latex succesfully compiled and dvisvgm succesfully created an svg.

The error when trying to compile:
```
Compilation error.
Please check that LaTeX is installed on your system and that its path is specified correctly.
```

In the terminal:
```
% where latex
/usr/bin/latex
/bin/latex
% where dvisvgm
/usr/bin/dvisvgm
/bin/dvisvgm
```

And in the scripting tab in blender:
```
>>> os.environ['PATH']
'/app/bin:/usr/bin'
```

Specifying the directories for latex and dvisvgm doesn't help.

**Comment by 1-Bart-1** [comment]
Found a workaround here: https://blender.stackexchange.com/questions/287707/latex2blender-latex-installation

But the apt version of blender is outdated, so it would be nice if the issue could be fixed in a different way.

**Comment by ghseeli** [comment]
Hi! I am traveling and do not have access to an Ubuntu machine right now. Did you specify the path as `/usr/bin` when you gave a custom path?

**Comment by 1-Bart-1** [comment]
Yes, I did! I had blender installed through flatpak. So the problem seems to arise when in a sandboxed environment. Using apt works fine, but then blender is outdated.

**Comment by ghseeli** [comment]
I see. I am not personally familiar with flatpak, but have you configured your blender installation to have access to `/usr/bin` folder? The error you are getting is consistent with the add-on not being able to access the filesystem. This SE post details some ways you might do this: https://askubuntu.com/questions/1086529/how-to-give-a-flatpak-app-access-to-a-directory

**Comment by 1-Bart-1** [comment]
Now I am getting this problem:
~ % flatpak run org.blender.Blender                            
F: Not sharing "/usr/bin" with sandbox: Path "/usr" is reserved by Flatpak
F: Not sharing "/usr/bin/latex" with sandbox: Path "/usr" is reserved by Flatpak
F: Not sharing "/usr/bin/dvisvgm" with sandbox: Path "/usr" is reserved by Flatpak
F: Not sharing "/bin/latex" with sandbox: Path "/bin" is reserved by Flatpak
F: Not sharing "/bin/dvisvgm" with sandbox: Path "/bin" is reserved by Flatpak

I guess I have to install latex somewhere else?

**Comment by 1-Bart-1** [comment]
I gave up: Flatpak is sandboxed so I don't think it will work.
