### ISSUE TITLE
Latex2blender  :  $\mapsto$

### ISSUE THREAD

**Issue by markcosgrove** [ghseeli/latex2blender#4]
I recently came across your Blender AddOn Latex2Blender and I've found it most useful.
I may have uncovered a bug but I'm not certain if it’s not me doing something wrong.

The Latex code $\mapsto$ does not seem to compile correctly. 

Thank you.

**Comment by ghseeli** [comment]
I am seeing this issue, too! I will try and look more into it today. In the meantime, it does appear that $\longmapsto$ compiles correctly, if that will work for your purposes.

**Comment by ghseeli** [comment]
Hi, @markcosgrove , could you please try installing this version (https://github.com/ghseeli/latex2blender/blob/ghseeli/4-mapsto-compiles-weird/latex2blender.py) and see if it compiled $\mapsto$ correctly for you? Thank you!

**Comment by markcosgrove** [comment]
Hi @ghseeli ,  yes, $\longmapsto$ works fine.
I'll try the new .py script tonight as well.
Thanks for your help.

**Comment by markcosgrove** [comment]
And the new script works!
$\mapsto$ looks good.

**Comment by ghseeli** [comment]
Thank you for your help! I have released the new version as v1.0.3.
